# Generated by Django 5.1.2 on 2024-11-04 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='video_id',
        ),
        migrations.AddField(
            model_name='task',
            name='video_input',

            field=models.CharField(default='SVRLi5T7MTw', max_length=255),
        ),
    ]
