# Generated by Django 5.1.2 on 2024-11-08 07:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_remove_task_video_id_task_video_input'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='lang',
            field=models.CharField(default='en', max_length=2),
        ),
        migrations.AlterField(
            model_name='task',
            name='video_input',
            field=models.CharField(max_length=255),
        ),
    ]
